import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const ibm_plex_mono = IBM_Plex_Mono({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ibm_plex_mono.className} md:w-7/12 container mx-auto`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
